[package]
name = "rust-roguelike-tutorial"
version = "0.1.0"
authors = ["marvinkassabian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.6.2"
specs = "0.15.1"
specs-derive = "0.4.0"
